variables:
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/chung28/gitlab-runner"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

compile:
  stage: build
  tags:
    - shell
    - quartz
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4

