variables:
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/chung28/gitlab-runner"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

compile:
  stage: build
  artifacts:
    paths:
      - ci-build
  tags:
    - shell
    - quartz
  script:
    - mkdir ci-build
    - cd ci-build
    - cmake ..
    - make -j 4

dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./dd_mms

param_prob:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./test_param_prob

