variables:
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/chung28/gitlab-runner"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

compile:
  stage: build
  artifacts:
    paths:
      - ci-build
  tags:
    - shell
    - quartz
  script:
    - mkdir ci-build
    - cd ci-build
    - cmake .. -DBUILD_SKETCHES=ON
    - make -j 4

dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./dd_mms

param_prob:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./test_param_prob

workflow:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./test_workflow

hdf5:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./test_hdf5

comp-topol:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - ./test_topol

multi_comp_dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  # rules:
  #   - exists:
  #       - ./ci-build/test/gmsh/multi_comp_dd_mms
  script:
    - cd ci-build/test/gmsh
    - if [ -f "./multi_comp_dd_mms" ]; then ./multi_comp_dd_mms; else echo "multi_comp_dd_mms does not exist. Passing the test."; fi

multi_comp_workflow:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test/gmsh
    - if [ -f "./test_multi_comp_workflow" ]; then ./test_multi_comp_workflow; else echo "test_multi_comp_workflow does not exist. Passing the test."; fi

