variables:
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/chung28/gitlab-runner"
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_FILE: "/g/g92/chung28/scaleuprom_env/scaleuprom_env.sif"

stages:
  - build
  - test

compile:
  stage: build
  artifacts:
    paths:
      - ci-build
  tags:
    - shell
    - quartz
  script:
    - mkdir ci-build
    - cd ci-build
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE cmake .. -DBUILD_SKETCHES=ON
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE make -j 4

parser:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./test_parser
    # - mpirun -n 4 ./test_parser

poisson_dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./poisson_dd_mms

stokes_dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./stokes_dd_mms

param_prob:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./test_param_prob

workflow:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./test_workflow

hdf5:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./test_hdf5

comp-topol:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./test_topol

block-smoother:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE ./test_block_smoother

multi_comp_dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  # rules:
  #   - exists:
  #       - ./ci-build/test/gmsh/multi_comp_dd_mms
  script:
    - cd ci-build/test/gmsh
    - echo 'if [ -f "./multi_comp_dd_mms" ]; then ./multi_comp_dd_mms; else echo "multi_comp_dd_mms does not exist. Passing the test."; fi' >> command.sh
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE sh command.sh

stokes_multi_comp_dd_mms:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test/gmsh
    - echo 'if [ -f "./stokes_multi_comp_dd_mms" ]; then ./stokes_multi_comp_dd_mms; else echo "stokes_multi_comp_dd_mms does not exist. Passing the test."; fi' >> command.sh
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE sh command.sh

multi_comp_workflow:
  stage: test
  dependencies:
    - compile
  tags:
    - shell
    - quartz
  script:
    - cd ci-build/test/gmsh
    - echo 'if [ -f "./test_multi_comp_workflow" ]; then ./test_multi_comp_workflow; else echo "test_multi_comp_workflow does not exist. Passing the test."; fi' >> command.sh
    - singularity exec --cleanenv -B $CUSTOM_CI_BUILDS_DIR $IMAGE_FILE sh command.sh

