name: CI
on: [push]
  # workflow_dispatch: {}
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types: [opened, labeled, synchronize]
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test ci
        run: |
            echo "test run"
        
  # docker-image:
  #   uses: ./.github/workflows/docker.yml
  # linux-build:
  #   runs-on: ubuntu-latest
  #   needs: [docker-image]
  #   container:
  #     image: ghcr.io/llnl/scaleuprom/scaleuprom_env:latest
  #     options: --user 1001 --privileged
  #     volumes:
  #       - /mnt:/mnt
  #   steps:
  #     - name: Cancel previous runs
  #       uses: styfle/cancel-workflow-action@0.11.0
  #       with:
  #         access_token: ${{ github.token }}
  #     - name: Set Swap Space
  #       uses: pierotofy/set-swap-space@master
  #       with:
  #         swap-size-gb: 10
  #     - name: Check out scaleupROM
  #       uses: actions/checkout@v3
  #     - name: Build scaleupROM
  #       run: |
  #           mkdir ${GITHUB_WORKSPACE}/build
  #           cd ${GITHUB_WORKSPACE}/build
  #           cmake .. -DBUILD_SKETCHES=On
  #           make -j 4
  #     - name: Upload the compiled artifacts
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: build-dir
  #         path: ${GITHUB_WORKSPACE}/build
  # linux-test:
  #   runs-on: ubuntu-latest
  #   needs: [docker-image, linux-build]
  #   container:
  #     image: ghcr.io/llnl/scaleuprom/scaleuprom_env:latest
  #     options: --user 1001 --privileged
  #     volumes:
  #       - /mnt:/mnt
  #   steps:
  #     - name: Cancel previous runs
  #       uses: styfle/cancel-workflow-action@0.11.0
  #       with:
  #         access_token: ${{ github.token }}
  #     - name: Set Swap Space
  #       uses: pierotofy/set-swap-space@master
  #       with:
  #         swap-size-gb: 10
  #     - name: Check out scaleupROM
  #       uses: actions/checkout@v3
  #     - name: Download the compiled artifacts
  #       uses: actions/download-artifact@master
  #       with:
  #         name: build-dir